### ISSUE TITLE
是当时最新的组件包么？

### ISSUE THREAD

**Issue by limingxinleo** [pifeifei/jingdong-jos-api-sdk#1]

**Comment by limingxinleo** [comment]
另外，兄弟还维护么？

**Comment by pifeifei** [comment]
是的， 当时最新的包，给的包，然后手动适配了 composer ，现在是不是最新的不清楚

**Comment by pifeifei** [comment]
> 另外，兄弟还维护么？

京东宙斯云仓接口， 跟京东物流不是一个, 虽然云仓也可以发快递

**Comment by limingxinleo** [comment]
京东联盟也是这个包

**Comment by limingxinleo** [comment]
这个包你还在用么？我想把基础代码升级一下，我这边php8.1，又是常驻内存项目，可能很多地方需要大改。

你看如果ok，你给我一个权限，我去做 v0.2 版本的修改，或者我fork出来自己维护一份

**Comment by pifeifei** [comment]
> 这个包你还在用么？我想把基础代码升级一下，我这边php8.1，又是常驻内存项目，可能很多地方需要大改。
> 
> 你看如果ok，你给我一个权限，我去做 v0.2 版本的修改，或者我fork出来自己维护一份

好的， 我给你权限，  换个 0.2 版本修改也行

**Comment by pifeifei** [comment]
添加管理了， 你看还需要其他的吗
@limingxinleo

**Comment by limingxinleo** [comment]
没有了~

多谢🤝
